[package]
name = "cismu-core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
tracing = "0.1.41"
bliss-audio = "0.10.1"
serde = { version = "1.0.219", features = ["derive"] }
specta = "=2.0.0-rc.22"
