[package]
name = "cismu-db"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
diesel = { version = "2.3.0", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
dotenvy = "0.15.7"
