[package]
name = "cismu-paths"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
directories = "6.0.0"
fs2 = "0.4.3"
once_cell = "1.21.3"
thiserror = "2.0.12"
tracing = "0.1.41"

[dev-dependencies]
tempfile = "3.20.0"
